### ISSUE TITLE
Index can be longer than length of string if slicing more than one character

### ISSUE THREAD

**Issue by camthecoder2020** [Ada-Developers-Academy/ada-build#215]
In lesson 02 Programming Grammar under Slicing/Indexing, it states the following:

"Note that if you provide an index greater than the length of the string, an IndexError will occur."

However, I think it's worth mentioning this only applies when slicing a single character. When splicing more than one character, you can use a last index in your range that's greater than the length of the string. It doesn't give an error message, but this wasn't explained as far as I can see.

**Comment by beccaelenzil** [comment]
Nice catch! The text has been updated.

Note that when you are indexing a string as in `string[i]` if you provide an index greater than the length of the string, an `IndexError` will occur. We'll leave it to you to investigate what happens when you provide an index greater than the length when slicing a string.
